module.exports = {
  apps: [
    {
      name: 'bazarvan-editor',
      script: 'server-dist/server.mjs',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || '8080',
      },
    },
    {
      name: 'bazarvan-ai-worker',
      script: 'server-dist/external-analysis-worker.mjs',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      restart_delay: 2000,
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        EXTERNAL_ANALYSIS_WORKER_POLL_MS: process.env.EXTERNAL_ANALYSIS_WORKER_POLL_MS || '5000',
        EXTERNAL_ANALYSIS_JOB_LEASE_SECONDS: process.env.EXTERNAL_ANALYSIS_JOB_LEASE_SECONDS || '300',
        EXTERNAL_ANALYSIS_RETRY_MINUTES: process.env.EXTERNAL_ANALYSIS_RETRY_MINUTES || '30',
        EXTERNAL_ANALYSIS_WORKER_CONCURRENCY: process.env.EXTERNAL_ANALYSIS_WORKER_CONCURRENCY || '5',
      },
    },
    {
      name: 'bazarvan-ai-job-worker',
      script: 'server-dist/ai-job-worker.mjs',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      restart_delay: 2000,
      kill_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        AI_JOB_WORKER_POLL_MS: process.env.AI_JOB_WORKER_POLL_MS || '1500',
        AI_JOB_LEASE_SECONDS: process.env.AI_JOB_LEASE_SECONDS || '300',
        AI_JOB_WORKER_CONCURRENCY: process.env.AI_JOB_WORKER_CONCURRENCY || '2',
        EXTERNAL_ANALYSIS_RETRY_MINUTES: process.env.EXTERNAL_ANALYSIS_RETRY_MINUTES || '30',
      },
    },
    {
      name: 'bazarvan-content-writing-worker',
      script: 'server-dist/content-writing-worker.mjs',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      restart_delay: 2000,
      kill_timeout: 15000,
      env: {
        NODE_ENV: 'production',
        CONTENT_WRITING_WORKER_POLL_MS: process.env.CONTENT_WRITING_WORKER_POLL_MS || '1500',
        CONTENT_WRITING_SESSION_LEASE_SECONDS: process.env.CONTENT_WRITING_SESSION_LEASE_SECONDS || '1800',
        CONTENT_WRITING_WORKER_CONCURRENCY: process.env.CONTENT_WRITING_WORKER_CONCURRENCY || '1',
      },
    },
  ],
};
