-- Lightweight Realtime wake signals let Hostinger workers sleep while their queues
-- are empty. The queue rows themselves are intentionally not published because they
-- can contain large article, competitor, or AI payloads.

create table if not exists public.worker_queue_signals (
  id bigint generated by default as identity primary key,
  queue_name text not null
    check (queue_name in ('ai_jobs', 'content_writing', 'client_page_crawl', 'external_analysis')),
  created_at timestamptz not null default now()
);

create index if not exists worker_queue_signals_queue_created_idx
  on public.worker_queue_signals(queue_name, created_at desc);

alter table public.worker_queue_signals enable row level security;

revoke all on public.worker_queue_signals from public, anon, authenticated;
grant select, insert, delete on public.worker_queue_signals to service_role;
grant usage, select on sequence public.worker_queue_signals_id_seq to service_role;

create or replace function public.emit_worker_queue_signal()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_queue_name text := nullif(btrim(coalesce(tg_argv[0], '')), '');
  v_is_ready boolean := false;
  v_was_ready boolean := false;
begin
  if v_queue_name is null then
    raise exception 'Worker queue signal name is required.' using errcode = '22023';
  end if;

  v_is_ready :=
    new.status = 'queued'
    or (
      new.status = 'retry_scheduled'
      and coalesce(new.next_attempt_at, now()) <= now()
    );

  if tg_op = 'UPDATE' then
    v_was_ready :=
      old.status = 'queued'
      or (
        old.status = 'retry_scheduled'
        and coalesce(old.next_attempt_at, now()) <= now()
      );
  end if;

  if v_is_ready and (tg_op = 'INSERT' or not v_was_ready) then
    insert into public.worker_queue_signals(queue_name)
    values (v_queue_name);

    -- Signals are transient wake hints; polling remains the reliability fallback.
    delete from public.worker_queue_signals
    where created_at < now() - interval '1 day';
  end if;

  return new;
end;
$$;

revoke all on function public.emit_worker_queue_signal() from public, anon, authenticated;

drop trigger if exists signal_ai_job_worker on public.ai_jobs;
create trigger signal_ai_job_worker
after insert or update of status, next_attempt_at on public.ai_jobs
for each row execute function public.emit_worker_queue_signal('ai_jobs');

drop trigger if exists signal_content_writing_worker on public.content_writing_sessions;
create trigger signal_content_writing_worker
after insert or update of status, next_attempt_at on public.content_writing_sessions
for each row execute function public.emit_worker_queue_signal('content_writing');

drop trigger if exists signal_client_page_crawl_worker on public.client_page_crawl_jobs;
create trigger signal_client_page_crawl_worker
after insert or update of status, next_attempt_at on public.client_page_crawl_jobs
for each row execute function public.emit_worker_queue_signal('client_page_crawl');

drop trigger if exists signal_external_analysis_worker on public.ai_external_analysis_jobs;
create trigger signal_external_analysis_worker
after insert or update of status, next_attempt_at on public.ai_external_analysis_jobs
for each row execute function public.emit_worker_queue_signal('external_analysis');

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'worker_queue_signals'
  ) then
    alter publication supabase_realtime add table public.worker_queue_signals;
  end if;
end;
$$;

comment on table public.worker_queue_signals is
  'Small transient Realtime signals that wake durable workers without publishing large queue rows.';
comment on function public.emit_worker_queue_signal() is
  'Emits a small wake signal when a durable queue receives immediately claimable work.';
