begin;

-- Google-facing titles and descriptions are part of the semantic response.
-- Keep the persistence check in Postgres so browser, API and worker flows all
-- agree on whether the combined result is ready.
create or replace function public.semantic_keywords_have_google_metadata(
  p_keywords jsonb
)
returns boolean
language sql
immutable
set search_path = public, pg_temp
as $$
  select
    jsonb_typeof(coalesce(p_keywords, '{}'::jsonb)->'googleTitles') = 'array'
    and jsonb_array_length(coalesce(p_keywords, '{}'::jsonb)->'googleTitles') = 2
    and not exists (
      select 1
      from jsonb_array_elements(coalesce(p_keywords, '{}'::jsonb)->'googleTitles') as title(value)
      where jsonb_typeof(title.value) <> 'string'
        or nullif(btrim(title.value #>> '{}'), '') is null
    )
    and jsonb_typeof(coalesce(p_keywords, '{}'::jsonb)->'googleDescriptions') = 'array'
    and jsonb_array_length(coalesce(p_keywords, '{}'::jsonb)->'googleDescriptions') = 2
    and not exists (
      select 1
      from jsonb_array_elements(coalesce(p_keywords, '{}'::jsonb)->'googleDescriptions') as description(value)
      where (
        jsonb_typeof(description.value) = 'object'
        and nullif(btrim(description.value->>'text'), '') is null
      )
      or (
        jsonb_typeof(description.value) = 'string'
        and nullif(btrim(description.value #>> '{}'), '') is null
      )
      or jsonb_typeof(description.value) not in ('object', 'string')
    );
$$;

-- Ready-status meta descriptions are retired. The two Google descriptions are
-- now generated together with alternative forms and LSI terms, before the
-- external-analysis sequence continues.
update public.app_settings
set
  value = coalesce(value, '{}'::jsonb) - 'autoGenerateMetaDescription',
  updated_at = now()
where key = 'system'
  and not is_secret;

drop trigger if exists enqueue_article_meta_description_from_article on public.articles;
drop trigger if exists reconcile_meta_description_automation_from_settings on public.app_settings;

create or replace function public.meta_description_automation_enabled()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select false;
$$;

with affected as (
  update public.ai_external_analysis_jobs as job
  set
    status = case when job.status = 'running' then 'running' else 'cancelled' end,
    cancel_requested_at = coalesce(job.cancel_requested_at, now()),
    next_attempt_at = case when job.status = 'running' then job.next_attempt_at else null end,
    locked_by = case when job.status = 'running' then job.locked_by else null end,
    locked_at = case when job.status = 'running' then job.locked_at else null end,
    lease_expires_at = case when job.status = 'running' then job.lease_expires_at else null end,
    completed_at = case when job.status = 'running' then job.completed_at else coalesce(job.completed_at, now()) end,
    last_error_code = 'ready_status_meta_description_retired',
    last_error = 'Automatic ready-status meta description generation was retired; Google suggestions are generated by semantic keywords.',
    progress = coalesce(job.progress, '{}'::jsonb) || jsonb_build_object(
      'stage', case when job.status = 'running' then 'cancellation_requested' else 'cancelled' end,
      'reason', 'ready_status_meta_description_retired',
      'updatedAt', now()
    ),
    updated_at = now()
  where job.job_type = 'meta_description_generation'
    and job.origin = 'auto'
    and job.status in ('waiting_for_prerequisites', 'queued', 'running', 'retry_scheduled', 'paused')
  returning job.id, job.status
)
update public.ai_external_analysis_runs as run
set
  status = 'cancelled',
  error_code = 'ready_status_meta_description_retired',
  error_message = 'Automatic ready-status meta description generation was retired.',
  finished_at = coalesce(run.finished_at, now())
from affected
where run.job_id = affected.id
  and affected.status <> 'running'
  and run.status = 'running';

-- Each worker run freezes all three semantic targets. Existing historical
-- runs are deliberately marked as not having attempted Google metadata so the
-- new target is allowed exactly one automatic run after this release.
create or replace function public.stamp_external_semantic_run_targets()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_input_snapshot jsonb := '{}'::jsonb;
begin
  select coalesce(job.input_snapshot, '{}'::jsonb)
  into v_input_snapshot
  from public.ai_external_analysis_jobs as job
  where job.id = new.job_id
    and job.job_type = 'semantic_keywords_lsi';

  if found then
    new.progress := coalesce(new.progress, '{}'::jsonb) || jsonb_build_object(
      'semanticTargetAttempt', jsonb_build_object(
        'secondaries', case
          when jsonb_typeof(v_input_snapshot->'needsSecondaries') = 'boolean'
            then (v_input_snapshot->>'needsSecondaries')::boolean
          else true
        end,
        'lsi', case
          when jsonb_typeof(v_input_snapshot->'needsLsi') = 'boolean'
            then (v_input_snapshot->>'needsLsi')::boolean
          else true
        end,
        'googleMetadata', case
          when jsonb_typeof(v_input_snapshot->'needsGoogleMetadata') = 'boolean'
            then (v_input_snapshot->>'needsGoogleMetadata')::boolean
          else true
        end
      )
    );
  end if;

  return new;
end;
$$;

update public.ai_external_analysis_runs as run
set progress = jsonb_set(
  coalesce(run.progress, '{}'::jsonb),
  '{semanticTargetAttempt}',
  coalesce(run.progress->'semanticTargetAttempt', '{}'::jsonb)
    || jsonb_build_object('googleMetadata', false),
  true
)
from public.ai_external_analysis_jobs as job
where job.id = run.job_id
  and job.job_type = 'semantic_keywords_lsi'
  and not (coalesce(run.progress->'semanticTargetAttempt', '{}'::jsonb) ? 'googleMetadata');

create or replace function public.enqueue_external_semantic_analysis_job_controlled(
  p_article_id uuid,
  p_origin text default 'auto'
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_requested_origin text := lower(btrim(coalesce(p_origin, 'auto')));
  v_manual boolean := false;
  v_force_regenerate boolean := false;
  v_settings jsonb := public.get_content_research_automation_settings();
  v_article public.articles%rowtype;
  v_state public.ai_external_analysis_article_state%rowtype;
  v_has_secondaries boolean := false;
  v_has_lsi boolean := false;
  v_has_google_metadata boolean := false;
  v_needs_secondaries boolean := false;
  v_needs_lsi boolean := false;
  v_needs_google_metadata boolean := false;
  v_attempted_secondaries boolean := false;
  v_attempted_lsi boolean := false;
  v_attempted_google_metadata boolean := false;
  v_execute_secondaries boolean := false;
  v_execute_lsi boolean := false;
  v_execute_google_metadata boolean := false;
  v_existing_job_id uuid;
  v_existing_status text;
  v_job_id uuid;
  v_idempotency_key text;
begin
  if v_requested_origin not in ('auto', 'manual', 'manual_regenerate', 'regenerate', 'manual_force') then
    v_requested_origin := 'auto';
  end if;
  v_manual := v_requested_origin <> 'auto';
  v_force_regenerate := v_requested_origin in ('manual_regenerate', 'regenerate', 'manual_force');

  perform pg_advisory_xact_lock(hashtextextended(
    'external-analysis-auto-once:' || p_article_id::text || ':semantic_keywords_lsi',
    0
  ));

  select article.* into v_article
  from public.articles as article
  where article.id = p_article_id;
  if v_article.id is null then return null; end if;

  select state.* into v_state
  from public.ai_external_analysis_article_state as state
  where state.article_id = p_article_id;
  if v_state.article_id is null
    or not v_state.semantic_ready
    or nullif(v_state.semantic_readiness_signature, '') is null then
    return null;
  end if;

  perform job.id
  from public.ai_external_analysis_jobs as job
  where job.article_id = p_article_id
    and job.job_type = 'semantic_keywords_lsi'
    and job.last_error_code is distinct from 'duplicate_task_suppressed'
  order by job.id
  for update;

  v_has_secondaries := public.external_analysis_has_competitor_value(
    coalesce(v_article.keywords, '{}'::jsonb)->'secondaries', 100
  );
  v_has_lsi := public.external_analysis_has_competitor_value(
    coalesce(v_article.keywords, '{}'::jsonb)->'lsi', 100
  );
  v_has_google_metadata := public.semantic_keywords_have_google_metadata(v_article.keywords);

  v_needs_secondaries := (v_force_regenerate or not v_has_secondaries)
    and (v_manual or coalesce((v_settings->>'autoGenerateAlternativeKeywords')::boolean, true));
  v_needs_lsi := (v_force_regenerate or not v_has_lsi)
    and (v_manual or coalesce((v_settings->>'autoGenerateLsiKeywords')::boolean, true));
  v_needs_google_metadata := (v_force_regenerate or not v_has_google_metadata)
    and (
      v_manual
      or coalesce((v_settings->>'autoGenerateAlternativeKeywords')::boolean, true)
      or coalesce((v_settings->>'autoGenerateLsiKeywords')::boolean, true)
    );

  if not v_needs_secondaries and not v_needs_lsi and not v_needs_google_metadata then
    return null;
  end if;

  if not v_manual then
    select
      coalesce(bool_or(case
        when jsonb_typeof(run.progress #> '{semanticTargetAttempt,secondaries}') = 'boolean'
          then (run.progress #>> '{semanticTargetAttempt,secondaries}')::boolean
        else true
      end), false),
      coalesce(bool_or(case
        when jsonb_typeof(run.progress #> '{semanticTargetAttempt,lsi}') = 'boolean'
          then (run.progress #>> '{semanticTargetAttempt,lsi}')::boolean
        else true
      end), false),
      coalesce(bool_or(case
        when jsonb_typeof(run.progress #> '{semanticTargetAttempt,googleMetadata}') = 'boolean'
          then (run.progress #>> '{semanticTargetAttempt,googleMetadata}')::boolean
        else false
      end), false)
    into v_attempted_secondaries, v_attempted_lsi, v_attempted_google_metadata
    from public.ai_external_analysis_runs as run
    join public.ai_external_analysis_jobs as job on job.id = run.job_id
    where job.article_id = p_article_id
      and job.job_type = 'semantic_keywords_lsi'
      and job.last_error_code is distinct from 'duplicate_task_suppressed';

    v_existing_job_id := public.find_external_analysis_stage_job(
      p_article_id, 'semantic_keywords_lsi', null
    );
    if (not v_needs_secondaries or v_attempted_secondaries)
      and (not v_needs_lsi or v_attempted_lsi)
      and (not v_needs_google_metadata or v_attempted_google_metadata) then
      return v_existing_job_id;
    end if;
  end if;

  v_execute_secondaries := v_needs_secondaries and (v_manual or not v_attempted_secondaries);
  v_execute_lsi := v_needs_lsi and (v_manual or not v_attempted_lsi);
  v_execute_google_metadata := v_needs_google_metadata
    and (v_manual or not v_attempted_google_metadata);

  select job.id, job.status
  into v_existing_job_id, v_existing_status
  from public.ai_external_analysis_jobs as job
  where job.article_id = p_article_id
    and job.job_type = 'semantic_keywords_lsi'
    and job.readiness_signature = v_state.semantic_readiness_signature
    and job.last_error_code is distinct from 'duplicate_task_suppressed'
  order by coalesce(job.completed_at, job.updated_at, job.created_at) desc
  limit 1
  for update;

  if v_existing_job_id is not null
    and v_existing_status = 'running' then
    return v_existing_job_id;
  end if;
  if not v_manual
    and v_existing_job_id is not null
    and v_existing_status in ('waiting_for_prerequisites', 'queued', 'retry_scheduled', 'paused') then
    return v_existing_job_id;
  end if;

  v_idempotency_key := 'semantic_keywords_lsi:' || v_state.semantic_readiness_signature;
  if v_existing_job_id is null then
    insert into public.ai_external_analysis_jobs (
      article_id, requested_by, job_type, origin, status, idempotency_key,
      readiness_signature, input_snapshot, progress, next_attempt_at, max_attempts
    ) values (
      p_article_id,
      coalesce(v_article.assigned_to, v_article.owner_id, v_article.created_by),
      'semantic_keywords_lsi',
      case when v_manual then 'manual' else 'auto' end,
      'queued',
      v_idempotency_key,
      v_state.semantic_readiness_signature,
      jsonb_build_object(
        'title', v_article.title,
        'plainText', v_article.plain_text,
        'keywords', coalesce(v_article.keywords, '{}'::jsonb),
        'goalContext', coalesce(v_article.goal_context, '{}'::jsonb),
        'articleLanguage', v_article.article_language,
        'articleUpdatedAt', v_article.updated_at,
        'readinessSignature', v_state.semantic_readiness_signature,
        'needsSecondaries', v_execute_secondaries,
        'needsLsi', v_execute_lsi,
        'needsGoogleMetadata', v_execute_google_metadata,
        'automaticOnceTargets', jsonb_build_object(
          'secondaries', v_execute_secondaries,
          'lsi', v_execute_lsi,
          'googleMetadata', v_execute_google_metadata
        ),
        'automationSettings', v_settings,
        'controlledOrigin', case when v_manual then 'manual' else 'auto' end,
        'forceRegenerateSemantic', v_force_regenerate
      ),
      jsonb_build_object(
        'stage', 'queued',
        'needsSecondaries', v_execute_secondaries,
        'needsLsi', v_execute_lsi,
        'needsGoogleMetadata', v_execute_google_metadata,
        'updatedAt', now()
      ),
      now(),
      1
    ) returning id into v_job_id;
  else
    v_job_id := v_existing_job_id;
    update public.ai_external_analysis_jobs as job
    set
      requested_by = coalesce(v_article.assigned_to, v_article.owner_id, v_article.created_by, job.requested_by),
      origin = case when v_manual then 'manual' else job.origin end,
      status = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then 'queued' else job.status end,
      idempotency_key = v_idempotency_key,
      input_snapshot = jsonb_build_object(
        'title', v_article.title,
        'plainText', v_article.plain_text,
        'keywords', coalesce(v_article.keywords, '{}'::jsonb),
        'goalContext', coalesce(v_article.goal_context, '{}'::jsonb),
        'articleLanguage', v_article.article_language,
        'articleUpdatedAt', v_article.updated_at,
        'readinessSignature', v_state.semantic_readiness_signature,
        'needsSecondaries', v_execute_secondaries,
        'needsLsi', v_execute_lsi,
        'needsGoogleMetadata', v_execute_google_metadata,
        'automaticOnceTargets', jsonb_build_object(
          'secondaries', v_execute_secondaries,
          'lsi', v_execute_lsi,
          'googleMetadata', v_execute_google_metadata
        ),
        'automationSettings', v_settings,
        'controlledOrigin', case when v_manual then 'manual' else 'auto' end,
        'forceRegenerateSemantic', v_force_regenerate
      ),
      result = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.result end,
      progress = jsonb_build_object(
        'stage', case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then 'queued' else job.status end,
        'needsSecondaries', v_execute_secondaries,
        'needsLsi', v_execute_lsi,
        'needsGoogleMetadata', v_execute_google_metadata,
        'updatedAt', now()
      ),
      last_error = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.last_error end,
      last_error_code = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.last_error_code end,
      next_attempt_at = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then now() else job.next_attempt_at end,
      locked_by = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.locked_by end,
      locked_at = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.locked_at end,
      lease_expires_at = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.lease_expires_at end,
      cancel_requested_at = null,
      completed_at = case when job.status in ('completed', 'failed', 'blocked', 'cancelled') then null else job.completed_at end,
      max_attempts = case when v_manual then greatest(job.max_attempts, job.attempt_count + 1) else greatest(1, job.attempt_count) end,
      updated_at = now()
    where job.id = v_job_id;
  end if;

  update public.ai_external_analysis_article_state as state
  set semantic_last_enqueued_signature = v_state.semantic_readiness_signature,
      updated_at = now()
  where state.article_id = p_article_id;

  return v_job_id;
end;
$$;

-- Preserve the established command builder, but place a Google-metadata gate
-- in front of it. The legacy builder creates the serial command chain; the
-- first command is changed to wait for the unified semantic job before the
-- transaction is committed, so no command can run early.
alter function public.enqueue_external_engineering_jobs_sequential_base(uuid, text)
  rename to enqueue_external_engineering_jobs_sequential_base_before_google_metadata;

create or replace function public.enqueue_external_engineering_jobs_sequential_base(
  p_article_id uuid,
  p_origin text
)
returns uuid[]
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_keywords jsonb := '{}'::jsonb;
  v_semantic_job_id uuid;
  v_job_ids uuid[] := array[]::uuid[];
begin
  select coalesce(article.keywords, '{}'::jsonb)
  into v_keywords
  from public.articles as article
  where article.id = p_article_id;
  if not found then return v_job_ids; end if;

  if public.semantic_keywords_have_google_metadata(v_keywords) then
    return public.enqueue_external_engineering_jobs_sequential_base_before_google_metadata(
      p_article_id, p_origin
    );
  end if;

  v_semantic_job_id := public.enqueue_external_semantic_analysis_job_controlled(
    p_article_id,
    case when lower(btrim(coalesce(p_origin, 'auto'))) = 'manual' then 'manual' else 'auto' end
  );
  if v_semantic_job_id is null then
    perform public.cancel_stale_external_engineering_jobs(p_article_id, null, true);
    return v_job_ids;
  end if;

  v_job_ids := public.enqueue_external_engineering_jobs_sequential_base_before_google_metadata(
    p_article_id, p_origin
  );
  if cardinality(v_job_ids) > 0 then
    update public.ai_external_analysis_jobs as job
    set
      status = 'waiting_for_prerequisites',
      depends_on_job_id = v_semantic_job_id,
      next_attempt_at = null,
      progress = coalesce(job.progress, '{}'::jsonb) || jsonb_build_object(
        'stage', 'waiting_for_prerequisites',
        'reason', 'unified_semantic_google_metadata_required',
        'updatedAt', now()
      ),
      updated_at = now()
    where job.id = v_job_ids[1]
      and job.status in ('waiting_for_prerequisites', 'queued', 'retry_scheduled', 'paused');
  end if;

  return v_job_ids;
end;
$$;

revoke all on function public.semantic_keywords_have_google_metadata(jsonb)
  from public, anon, authenticated;
revoke all on function public.enqueue_external_engineering_jobs_sequential_base_before_google_metadata(uuid, text)
  from public, anon, authenticated;
revoke all on function public.enqueue_external_engineering_jobs_sequential_base(uuid, text)
  from public, anon, authenticated;
revoke all on function public.enqueue_external_semantic_analysis_job_controlled(uuid, text)
  from public, anon, authenticated;
revoke all on function public.meta_description_automation_enabled()
  from public, anon, authenticated;
grant execute on function public.semantic_keywords_have_google_metadata(jsonb) to service_role;
grant execute on function public.enqueue_external_engineering_jobs_sequential_base(uuid, text) to service_role;
grant execute on function public.enqueue_external_semantic_analysis_job_controlled(uuid, text) to service_role;
grant execute on function public.meta_description_automation_enabled() to service_role;

comment on function public.semantic_keywords_have_google_metadata(jsonb)
  is 'Returns true only when the unified semantic result has exactly two Google titles and two descriptions.';
comment on function public.enqueue_external_semantic_analysis_job_controlled(uuid, text)
  is 'Queues unified alternative forms, LSI terms, and two Google titles and descriptions; manual_regenerate replaces all three targets.';
comment on function public.enqueue_external_engineering_jobs_sequential_base(uuid, text)
  is 'Queues the engineering chain only after unified semantic Google metadata is available.';
comment on function public.meta_description_automation_enabled()
  is 'Always false: ready-status meta-description automation was retired in favor of unified semantic Google metadata.';

notify pgrst, 'reload schema';
commit;
